import { Gem, Sparkles, Shirt, Heart } from 'lucide-react';
import type { AnalysisResult, ColourInfo } from '@/types';
import ColourCard from '@/components/ColourCard';
import { getMatchColour } from '@/utils/analysis';

interface ColourStripProps { title: string; colours: ColourInfo[]; onSelect: (c: ColourInfo) => void; }
export function ColourStrip({ title, colours, onSelect }: ColourStripProps) { return <div><h3 className="font-semibold text-neutral-900 mb-3">{title}</h3><div className="flex gap-3 overflow-x-auto no-scrollbar pb-2">{colours.map((c) => <div key={`${c.name}-${c.hex}`} className="min-w-[105px]"><ColourCard colour={c} onSelect={onSelect} compact /></div>)}</div></div>; }

export function StyleGuide({ result }: { result: AnalysisResult }) { return <section className="rounded-3xl bg-gradient-to-br from-neutral-100 to-white border border-neutral-200 p-6 sm:p-8"><div className="flex items-center gap-2 mb-4"><Sparkles className="w-5 h-5 text-neutral-800" /><h2 className="font-display text-2xl font-bold">Your Personal Style Guide</h2></div><p className="text-neutral-600 leading-relaxed max-w-3xl">{result.styleGuide}</p></section>; }

export function RecommendationSections({ result, onSelect }: { result: AnalysisResult; onSelect: (c: ColourInfo) => void }) { const fashion = result.fashionRecommendations; const makeup = result.makeupRecommendations; return <div className="space-y-12"><section><div className="flex items-center gap-3 mb-6"><Shirt className="w-6 h-6" /><div><h2 className="font-display text-3xl font-bold">What should you wear?</h2><p className="text-sm text-neutral-500">Colour ideas for every part of your wardrobe.</p></div></div><div className="space-y-7"><ColourStrip title="Dresses" colours={fashion.dresses} onSelect={onSelect} /><ColourStrip title="Sarees" colours={fashion.sarees} onSelect={onSelect} /><ColourStrip title="Blouses" colours={fashion.blouses} onSelect={onSelect} /><ColourStrip title="Shirts / Tops" colours={fashion.shirtsTops} onSelect={onSelect} /><ColourStrip title="Accessories" colours={fashion.accessories} onSelect={onSelect} /></div></section><section><div className="flex items-center gap-3 mb-6"><Gem className="w-6 h-6" /><div><h2 className="font-display text-3xl font-bold">Jewellery that complements your palette</h2><p className="text-sm text-neutral-500">Aesthetic guidance, not a scientific measurement.</p></div></div><div className="grid grid-cols-2 md:grid-cols-4 gap-4">{result.jewelleryRecommendations.map((item) => <div key={item.metal} className="rounded-2xl border border-neutral-100 bg-white p-5"><div className="w-12 h-12 rounded-full mb-4 border-4 border-white shadow" style={{ backgroundColor: item.hex }} /><h3 className="font-semibold">{item.metal}</h3><p className="text-xs font-semibold mt-2" style={{ color: getMatchColour(item.match) }}>{item.match}</p><p className="text-xs text-neutral-500 mt-2 leading-relaxed">{item.description}</p></div>)}</div></section><section><div className="flex items-center gap-3 mb-6"><Sparkles className="w-6 h-6" /><div><h2 className="font-display text-3xl font-bold">Makeup Colour Guide</h2><p className="text-sm text-neutral-500">Try these shades for a cohesive look.</p></div></div><div className="grid md:grid-cols-2 gap-6">{[['Lip Colours', makeup.lipColours], ['Blush', makeup.blush], ['Eyeshadow', makeup.eyeshadow], ['Nail Colours', makeup.nailColours]].map(([title, colours]) => <ColourStrip key={title as string} title={title as string} colours={colours as ColourInfo[]} onSelect={onSelect} />)}</div></section></div>; }

export function ShareSave({ result, favourites }: { result: AnalysisResult; favourites: string[] }) { const save = () => localStorage.setItem('colormatch-profile', JSON.stringify({ result, favourites })); const share = async () => { const text = `My ColorMatch AI profile: ${result.profile.season} — ${result.profile.undertone} undertone`; if (navigator.share) await navigator.share({ title: 'My ColorMatch AI Palette', text }); else { await navigator.clipboard?.writeText(text); alert('Your profile summary was copied to the clipboard.'); } }; return <div className="flex flex-col sm:flex-row gap-3"><button onClick={save} className="flex-1 py-3.5 rounded-xl bg-neutral-900 text-white font-medium flex items-center justify-center gap-2"><Heart className="w-4 h-4" /> Save My Palette</button><button onClick={() => void share()} className="flex-1 py-3.5 rounded-xl border border-neutral-200 font-medium flex items-center justify-center gap-2"><Sparkles className="w-4 h-4" /> Share My Palette</button></div>; }
